SELECT *
FROM DIANRESERVATION A
WHERE EXISTS(
        SELECT *
        FROM DIANRESERVATION B
        WHERE B.START_DATE < A.END_DATE
        AND B.END_DATE > A.START_DATE
        AND B.RESERVATION_ID <> A.RESERVATION_ID
        AND B.USER_ID = A.USER_ID
        );