SELECT FFF.OWNER, DDD.FIRST_NAME, DDD.LAST_NAME, FFF.RATIO
FROM (SELECT AAA.OWNER, ((AAA.NEW_NIGHTS - BBB.OLD_NIGHTS)/BBB.OLD_NIGHTS)AS RATIO
FROM (SELECT OWNER, SUM(N_NIGHTS)AS NEW_NIGHTS
FROM (SELECT A.VILLA_ID, A.N_NIGHTS, B.OWNER
FROM (SELECT VILLA_ID, SUM(NIGHTS)AS N_NIGHTS
FROM (SELECT VILLA_ID, (END_DATE - START_DATE)AS NIGHTS
FROM DIANRESERVATION 
WHERE END_DATE < '01-SEP-2014' AND START_DATE > '31-DEC-2013')
GROUP BY VILLA_ID)A JOIN DIANVILLA B ON A.VILLA_ID = B.VILLA_ID)
GROUP BY OWNER)AAA JOIN (SELECT OWNER, SUM(O_NIGHTS)AS OLD_NIGHTS
FROM (SELECT A.VILLA_ID, A.O_NIGHTS, B.OWNER
FROM (SELECT VILLA_ID, SUM(NIGHTS)AS O_NIGHTS
FROM (SELECT VILLA_ID, (END_DATE - START_DATE)AS NIGHTS
FROM DIANRESERVATION 
WHERE END_DATE < '01-SEP-2013' AND START_DATE > '31-DEC-2012')
GROUP BY VILLA_ID)A JOIN DIANVILLA B ON A.VILLA_ID = B.VILLA_ID)
GROUP BY OWNER)BBB ON AAA.OWNER = BBB.OWNER)FFF JOIN DIANUSER DDD ON 
FFF.OWNER = DDD.ID
WHERE FFF.RATIO > 0.1
;