SELECT BBB.FIRST_NAME, BBB.LAST_NAME, AAA.NUM
FROM(SELECT OWNER, COUNT(VILLA_ID)AS NUM
FROM (SELECT DIANVILLA.VILLA_ID, DIANVILLA.OWNER
FROM DIANVILLA JOIN DIANUSER ON DIANUSER.ID = DIANVILLA.OWNER)
GROUP BY OWNER
ORDER BY COUNT(VILLA_ID)DESC)AAA JOIN DIANUSER BBB ON AAA.OWNER = BBB.ID
;