

SELECT DISTINCT E.FIRST_NAME, E.LAST_NAME, E.ID
FROM (SELECT USER_ID
FROM (SELECT *
FROM DIANCOUPON A
WHERE A.DISCOUNT > 10) B JOIN DIANRESERVATION C ON B.COUPON_ID = C.COUPON_ID)D
JOIN DIANUSER E ON D.USER_ID = E.ID
;
