

SELECT AVG((SYSDATE - DIANUSER.DOB)/366) AS AVERAGE
FROM DIANUSER JOIN (SELECT DIANUSER.ID, DIANUSER.FIRST_NAME, DIANUSER.LAST_NAME
FROM DIANUSER JOIN (SELECT *
FROM DIANRESERVATION
WHERE START_DATE > '31-AUG-2013' AND START_DATE < '01-JAN-2014')ABC
ON DIANUSER.ID = ABC.USER_ID)FFF ON DIANUSER.ID = FFF.ID
;