SELECT * 
FROM (SELECT VILLA_ID, SUM(END_DATE - START_DATE)AS NIGHTS
FROM DIANRESERVATION 
WHERE START_DATE >= '01-JAN-14' AND END_DATE <= '31-DEC-2014'
GROUP BY VILLA_ID
ORDER BY SUM(END_DATE - START_DATE) DESC) 
WHERE ROWNUM = 1
;