


SELECT GGG.USER_ID, GGG.NUMOFMAXREVIEW, C.FIRST_NAME, C.LAST_NAME
FROM (SELECT USER_ID, NUMOFMAXREVIEW
FROM (SELECT  USER_ID, COUNT(USER_ID)AS NUMOFMAXREVIEW
FROM (SELECT AAA.USER_ID, AAA.VILLA_ID, FFF.NUM
FROM (SELECT A.REVIEW_ID, A.LIKE_NUM, B.USER_ID, B.VILLA_ID
FROM (SELECT REVIEW_ID, COUNT(USER_ID)AS LIKE_NUM
FROM DIANLIKEDREVIEWS
GROUP BY REVIEW_ID)A JOIN DIANREVIEW B ON A.REVIEW_ID = B.REVIEW_ID) AAA JOIN
(SELECT VILLA_ID, MAX(LIKE_NUM)AS NUM
FROM (SELECT A.REVIEW_ID, A.LIKE_NUM, B.USER_ID, B.VILLA_ID
FROM (SELECT REVIEW_ID, COUNT(USER_ID)AS LIKE_NUM
FROM DIANLIKEDREVIEWS
GROUP BY REVIEW_ID)A JOIN DIANREVIEW B ON A.REVIEW_ID = B.REVIEW_ID)
GROUP BY VILLA_ID)FFF ON (AAA.VILLA_ID = FFF.VILLA_ID AND AAA.LIKE_NUM = FFF.NUM))
GROUP BY USER_ID
ORDER BY COUNT(USER_ID) DESC)
WHERE ROWNUM = 1)GGG JOIN DIANUSER C ON GGG.USER_ID = C.ID
;