


SELECT AAA.OWNER, (AAA.NUM/BBB.TOTALNUM)AS RATIO
FROM (SELECT OWNER, COUNT(DISTINCT VILLA_ID) AS NUM
FROM (SELECT VILLA_ID, OWNER
FROM DIANVILLA
MINUS
SELECT B.VILLA_ID, B.OWNER
FROM (SELECT DISTINCT VILLA_ID
FROM DIANRESERVATION
WHERE START_DATE <= '15-AUG-2014' AND END_DATE >= '15-AUG-2014')A JOIN DIANVILLA B 
ON A.VILLA_ID = B.VILLA_ID)
GROUP BY OWNER)AAA JOIN ( SELECT OWNER, COUNT(DISTINCT VILLA_ID)AS TOTALNUM
FROM DIANVILLA
GROUP BY OWNER)BBB ON AAA.OWNER = BBB.OWNER
;